#ifndef P206_COMMON_VARIABLE_H_
#define P206_COMMON_VARIABLE_H_

#define CONTOUR_SIZE_MULTIPLE_CEIL 2
#define CONTOUR_SIZE_MULTIPLE_ROOF 0.5

#define ERRNO_EXIF_OK 0
#define ERRNO_EXIF_FILE_OPEN_FAILED 1
#define ERROR_EXIF_NOT_JPEG 2
#define ERROR_EXIF_NO_EXIF_IN_JPG 3


#endif // !P206_COMMON_VARIABLE_H_